# Generated by Django 4.2.2 on 2023-06-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_tenagakerja_permintaanproduk_permintaanpemasok_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField(max_length=5000)),
                ('gambar', models.ImageField(upload_to='assets', verbose_name='')),
                ('gambar_url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='umkm',
            old_name='no_ktp_sim',
            new_name='nik',
        ),
        migrations.AddField(
            model_name='umkm',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='umkm',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fasilitas',
            name='jenis',
            field=models.CharField(choices=[('ISO', 'ISO'), ('SNI', 'SNI'), ('SERTIFIKAT HALAL', 'SERTIFIKAT HALAL'), ('MEREK DAGANG', 'MEREK DAGANG'), ('UJI PRODUK', 'UJI PRODUK'), ('ALAT/MESIN', 'ALAT/MESIN'), ('Lainnya', 'Lainnya')], max_length=255),
        ),
        migrations.AlterField(
            model_name='jenisprodukkoperasi',
            name='komoditi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='jml_anggota',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='jml_karyawan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pemakaianenergi',
            name='jenis',
            field=models.CharField(choices=[('PLN', 'PLN'), ('Bahan Bakar Generator/Genset', 'Bahan Bakar Generator/Genset'), ('Bahan Bakar Gas LPG (3kg/12kg)', 'Bahan Bakar Gas LPG (3kg/12kg)'), ('Air (PDAM/HIPAM/Sumur)', 'Air (PDAM/HIPAM/Sumur)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='perijinan',
            name='jenis',
            field=models.CharField(choices=[('NIB', 'NIB'), ('P-IRT', 'P-IRT'), ('NPWP', 'NPWP'), ('MERK', 'MERK'), ('HALAL', 'HALAL'), ('BPOM', 'BPOM'), ('Akta Pendirian', 'Akta Pendirian'), ('Lainnya', 'Lainnya')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tenagakerja',
            name='pendidikan',
            field=models.CharField(choices=[('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('S1/S2/S3', 'S1/S2/S3')], max_length=255),
        ),
    ]
