# Generated by Django 4.2.2 on 2023-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_rename_asal_bahan_baku_bahanbaku_asal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
