# Generated by Django 4.2.2 on 2023-07-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_detail_is_adminsi_detail_is_koperasi_detail_is_umkm'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporankeuangan',
            name='beban_ymh_dibayar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laporankeuangan',
            name='hutang_lain_lain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laporankeuangan',
            name='hutang_usaha',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laporankeuangan',
            name='simpanan_berjangka',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laporankeuangan',
            name='simpanan_sukarela',
            field=models.IntegerField(null=True),
        ),
    ]
