# Generated by Django 4.2.2 on 2023-07-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_remove_detail_is_adminsi_remove_detail_is_koperasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_plut', models.ImageField(upload_to='assets', verbose_name='')),
                ('logo_sidaku', models.ImageField(upload_to='assets', verbose_name='')),
                ('ket_plut', models.CharField(max_length=100)),
                ('ket_sidaku', models.CharField(max_length=100)),
                ('alamat_plut', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('link_ig', models.CharField(max_length=100)),
                ('link_fb', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KontakPelayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_nahub1', models.ImageField(upload_to='assets', verbose_name='')),
                ('fp_nahub2', models.ImageField(upload_to='assets', verbose_name='')),
                ('nahub1', models.CharField(max_length=50)),
                ('nahub2', models.CharField(max_length=50)),
                ('wa_nahub1', models.CharField(max_length=20)),
                ('wa_nahub2', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='berita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='koperasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='umkm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
