# Generated by Django 4.2.2 on 2023-07-09 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0044_informasi_kontakpelayanan_berita_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakta',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporankeuangan',
            name='biaya_penysh_piutang_tak_tertagih',
            field=models.IntegerField(null=True),
        ),
    ]
