# Generated by Django 4.2.2 on 2023-07-10 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0045_fakta_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakta',
            name='owner',
        ),
        migrations.AddField(
            model_name='koperasi',
            name='pemilik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_koperasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='umkm',
            name='pemilik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_umkm', to=settings.AUTH_USER_MODEL),
        ),
    ]
