# Generated by Django 4.2.2 on 2023-07-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_fakta_owner_koperasi_pemilik_umkm_pemilik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alatproduksi',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bahanbaku',
            name='asal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bahanbaku',
            name='jenis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fakta',
            name='isi',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fakta',
            name='judul',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fasilitas',
            name='jenis',
            field=models.CharField(choices=[('ISO', 'ISO'), ('SNI', 'SNI'), ('SERTIFIKAT HALAL', 'SERTIFIKAT HALAL'), ('MEREK DAGANG', 'MEREK DAGANG'), ('UJI PRODUK', 'UJI PRODUK'), ('ALAT/MESIN', 'ALAT/MESIN'), ('Lainnya', 'Lainnya')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fasilitas',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jenisprodukkoperasi',
            name='satuan',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jenisprodukumkm',
            name='satuan',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='badan_hukum',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='bendahara',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='jenis',
            field=models.CharField(choices=[('Konsumen', 'Konsumen'), ('Simpan Pinjam', 'Simpan Pinjam'), ('Jasa', 'Jasa'), ('Produsen', 'Produsen'), ('Pemasaran', 'Pemasaran')], max_length=13),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='ketua',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='nib',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='nik',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='pengawas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='pengelola',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='produk_unggulan',
            field=models.ImageField(upload_to='assets', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='sekretaris',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paparan',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pelatihan',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pelatihan',
            name='tempat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pemakaianenergi',
            name='jenis',
            field=models.CharField(choices=[('PLN', 'PLN'), ('Bahan Bakar Generator/Genset', 'Bahan Bakar Generator/Genset'), ('Bahan Bakar Gas LPG (3kg/12kg)', 'Bahan Bakar Gas LPG (3kg/12kg)'), ('Air (PDAM/HIPAM/Sumur)', 'Air (PDAM/HIPAM/Sumur)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pemakaianenergi',
            name='keterangan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='penilaianpemasok',
            name='kualitas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='penilaianpemasok',
            name='nama_pemasok',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='penilaianpemasok',
            name='pengiriman',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perijinan',
            name='jenis',
            field=models.CharField(choices=[('NIB', 'NIB'), ('P-IRT', 'P-IRT'), ('NPWP', 'NPWP'), ('MERK', 'MERK'), ('HALAL', 'HALAL'), ('BPOM', 'BPOM'), ('Akta Pendirian', 'Akta Pendirian'), ('Lainnya', 'Lainnya')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perijinan',
            name='nomor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='permintaanpemasok',
            name='bulan',
            field=models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=10),
        ),
        migrations.AlterField(
            model_name='permintaanpemasok',
            name='pemasok',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='permintaanpemasok',
            name='permintaan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='permintaanpemasok',
            name='produksi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='permintaanproduk',
            name='bulan',
            field=models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=10),
        ),
        migrations.AlterField(
            model_name='permintaanproduk',
            name='permintaan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='permintaanproduk',
            name='produksi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produkhukum',
            name='kategori',
            field=models.CharField(choices=[('Undang-Undang', 'Undang-Undang'), ('Perancangan Undang-Undang', 'Perancangan Undang-Undang'), ('Peraturan Pemerintah', 'Peraturan Pemerintah'), ('Peraturan Presiden', 'Peraturan Presiden'), ('Keputusan dan Intruksi Presiden', 'Keputusan dan Intruksi Presiden'), ('Peraturan Menteri', 'Peraturan Menteri'), ('Keputusan Menteri', 'Keputusan Menteri'), ('Keputusan Deputi', 'Keputusan Deputi'), ('Peraturan Terkait', 'Peraturan Terkait'), ('Petunjuk Pelaksanaan', 'Petunjuk Pelaksanaan'), ('Surat Edaran', 'Surat Edaran')], max_length=35),
        ),
        migrations.AlterField(
            model_name='produkhukum',
            name='nama',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rapatkoordinasi',
            name='kategori',
            field=models.CharField(choices=[('Undang-Undang', 'Undang-Undang'), ('Perancangan Undang-Undang', 'Perancangan Undang-Undang'), ('Peraturan Pemerintah', 'Peraturan Pemerintah'), ('Peraturan Presiden', 'Peraturan Presiden'), ('Keputusan dan Intruksi Presiden', 'Keputusan dan Intruksi Presiden'), ('Peraturan Menteri', 'Peraturan Menteri'), ('Keputusan Menteri', 'Keputusan Menteri'), ('Keputusan Deputi', 'Keputusan Deputi'), ('Peraturan Terkait', 'Peraturan Terkait'), ('Petunjuk Pelaksanaan', 'Petunjuk Pelaksanaan'), ('Surat Edaran', 'Surat Edaran')], max_length=35),
        ),
        migrations.AlterField(
            model_name='rapatkoordinasi',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenagakerja',
            name='jenis',
            field=models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tenagakerja',
            name='pendidikan',
            field=models.CharField(choices=[('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('S1/S2/S3', 'S1/S2/S3')], max_length=15),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='bentuk',
            field=models.CharField(choices=[('Perorangan', 'Perorangan'), ('CV', 'CV'), ('UD', 'UD'), ('Koperasi', 'Koperasi'), ('Lainnya', 'Lainnya')], max_length=10),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='bidang',
            field=models.CharField(choices=[('Makanan dalam Kemasan', 'Makanan dalam Kemasan'), ('Minuman dalam Kemasan', 'Minuman dalam Kemasan'), ('Kerajinan', 'Kerajinan'), ('Perdagangan', 'Perdagangan'), ('Jasa', 'Jasa'), ('Lainnya', 'Lainnya')], max_length=25),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='nama_pemilik',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='nama_usaha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='nik',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='nomor_anggota',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='skala',
            field=models.CharField(choices=[('Mikro', 'Mikro'), ('Kecil', 'Kecil'), ('Menengah', 'Menengah')], max_length=8),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='telepon',
            field=models.CharField(max_length=13),
        ),
    ]
